@extends('layouts.pages')

@section('content')
	<main id="main" class="site-main" role="main">

		<article id="post-80" class="post-80 page type-page status-publish hentry">
			<header class="entry-header">
				<div class="interior-head">
					<h1 class="interior-head">{{$page_title}}</h1>	
				</div>
			</header><!-- .entry-header -->

			<div class="entry-content">
				<div class="interior">
					<h3>Terms and Conditions</h3>
					<h5>1. ACCEPTANCE OF TERMS.</h5>
					<h6>1.1 Overview.</h6>
					<p>The following terms and conditions (this "TAC") govern all use of the <a href="/">www.raceit.com </a>website (the "Site"), partner websites, and the services and software available on or through the Site (taken together with the Site, collectively, the "Service"). The Service is owned and operated by US RaceWorks, LLC. ("Race IT"). The Service is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on the Site by Race IT. BY USING OR ACCESSING ANY PART OF THE SERVICE, YOU AGREE TO ALL OF THE TERMS AND CONDITIONS CONTAINED HEREIN; IF YOU DO NOT AGREE TO ANY OF SUCH TERMS AND CONDITIONS, DO NOT USE OR ACCESS THE SERVICE.</p>
					<h6>1.2 Modification.</h6>
					<p>Race IT reserves the right, at its sole discretion, to modify or replace any of the terms or conditions of this TAC at any time. It is your responsibility to check this TAC periodically for changes. Your continued use of the Service following the posting of any changes to this TAC constitutes acceptance of those changes. If any change to this TAC is not acceptable to you, your sole remedy is to cease accessing, browsing and otherwise using the Service.</p>
					<h5>2. DESCRIPTION OF Race IT.</h5>
					<p>Race IT provides a simple and quick means for registered users who are event organizers and planners ("Organizers") to collect event registration fees for their events online through the Internet from registered users who want to attend such events ("Buyers"). Organizers may visit the Site, fill out a questionnaire about their event, including pricing, location, products, charities, etc., and collect event registration fees online directly from Buyers. Payments are all transacted through the Race IT payment processing gateway (the "Gateway"). For more information, please see <a href="/" target="blank">http://www.raceit.com</a>. This TAC applies to you and your use of the Service regardless of whether you are an Event Organizer, Buyer or other user of the Service.</p>
					<h5>3. YOUR USE OF THE SERVICE.</h5>
					<h6>3.1 The Service.</h6>
					<p>You shall use the Service only for purposes that are permitted by this TAC and any applicable laws and regulations (foreign and domestic). You shall not, nor permit anyone else to, directly or indirectly: (i) modify or otherwise create derivatives of any part of the Service; (ii) reverse engineer, disassemble, decompile or otherwise attempt to discover the source code or structure, sequence and organization of all or any part of the Service (except that this restriction shall not apply to the limited extent restrictions on reverse engineering are prohibited by applicable local law); (iii) rent, lease, resell, distribute or use the Service for timesharing, service bureau, or commercial purposes (except for the limited commercial purpose of selling event registrations through the Service as an Organizer); (iv) remove or alter any proprietary notices or labels on or in the Service; or (v) engage in any activity that interferes with or disrupts the Service. Race IT may change, suspend or discontinue the Service, including any feature of the Service or any Content (as defined below) made available in connection with the Service.</p>
					<h6>3.2 Software.</h6>
					<p>If you are allowed to download any software in connection with the Service ("Software"), subject to the terms and conditions of this TAC, Race IT grants you a personal, nontransferable, nonsublicensable, revocable, terminable, nonexclusive license to use the Software solely for your personal use, and only in accordance with this TAC and the written instructions/directions (if any) provided by Race IT. For clarity, the Software will be deemed a part of the "Service" hereunder.</p>
					<h6>3.3 Shipping.</h6>
					<p>Shipping times for physical goods or online delivery/fulfillment of a service vary depending on the terms and guidelines outlined by each event. Please inquire with the event offering the product/service if you are unsure on the delivery time/fulfillment instructions.</p>
					<h5>4. PAYMENT METHODS.</h5>
					<p>There is one form of payment processing for Organizers which requires the use of the Gateway for the collection of event registration fees. Depending on the payment processing option the Organizer elects when using the Service, monetary payments will be made to the Organizer by Race IT.</p>
					<h6>&nbsp;(a) Gateway; Payment Process.</h6>
					<p>When an Organizer elects to use the Service for the collection of event registration fees, payment processing occurs directly by Race IT. Under the Service, (i) Race IT will collect all event registration fees on behalf of the Organizer from the Buyer and deduct all applicable service charges from the event registration fees passed along to the Organizer.; (ii) Race IT will mail all payments to the Organizer (event registration fees minus applicable service charges) at the address that the Organizer accurately provides on the Site; and (iii) Race IT will submit payment for the balance due to the Organizer within fifteen (15) business days after the event end date for the event to which the registration fees correspond, provided that Race IT reserves the right to withhold funds at any time as Race IT determines to be necessary for the processing and settlement of all returns, disputed charges, customer complaints, allegations of fraud and other discrepancies. All sales, fees, charges, and funds are payable in U.S. Dollars, or other foreign currencies accepted by Race IT. For all sales, fees, charges, and funds paid in foreign currency, Race IT will collect and disperse the funds in the foreign currency used.</p>
					<h6>(b) Refunds.</h6>
					<p>(i) Under the Service, it is the responsibility of the Organizer to communicate its refund policy to Buyers and to issue refunds on the behalf of Buyers via the Service. Organizer shall ensure that its refund policy is consistent with the terms of this Agreement and the payment and refund mechanics of the Service. Refunds issued by Organizer will be processed within thirty (30) days after Organizer instructs the issuance of the refunds via the Service. No payments shall be made to an Organizer from Race IT with respect to any event that is cancelled. If a Buyer desires to request a refund, Buyer must request the refund from the Organizer (either before the event or shortly after the event, to permit the Organizer sufficient time to issue the refund). All communications or disputes regarding refunds are between the Organizer and Buyer and Race IT will not be responsible or liable for refunds or the lack thereof issued in the course of the use of the Full Service option. (ii) Notwithstanding the foregoing, whether you are using the Service as an Organizer, Buyer or otherwise, you acknowledge and agree that Race IT shall have the right to force a refund of any or all funds at any time for any reason or no reason, including without limitation if Race IT receives complaints from a substantial number (as determined by Race IT in its sole discretion) of Buyers with respect to an Organizer or the applicable event, or Race IT determines in its sole discretion that Organizer has engaged in any fraudulent activity or made any misrepresentations.</p>
					<p>There are no refunds for any transaction for registrations, donations, products, or any other service offered through raceit.com or any of its affiliates unless expressly stated otherwise.</p>
					<h6>(c) Credit Card Chargebacks.</h6>
					<p>Chargeback notifications from use of the Service (initiated by the Buyer with their credit card provider) are sent directly to Race IT via the constituent merchant banks.&nbsp; Race IT will be the sole and direct channel of correspondence in all chargeback proceedings.&nbsp; Race IT will utilize all available resources to contest or address each chargeback directly with the merchant bank in the time allotted for response.&nbsp;&nbsp;&nbsp; Chargeback cases where Race IT does not successfully secure a reversal or deems the chargeback to be warranted as stated, shall be charged back to the Organizer of such event.&nbsp;&nbsp;Race IT shall either (i) deduct these costs, and any associated fees from the merchant bank,&nbsp;from such Organizer’s outstanding balance, whether for that particular event or for any other event that such Organizer lists through the Service; or (ii) send an invoice to such Organizer for such costs if no balance exists. If payment for such invoice is not received by Race IT within thirty (30) days, Race IT reserves the right, at Race IT’s sole discretion, to terminate such Organizer’s registration for the Service and to cancel all other events listed by such Organizer as provided herein. In accordance with and without limiting Section 12, all communications and disputes regarding chargebacks are between the Organizer and Buyer and Race IT will not be responsible or liable in any way for chargebacks issued in the course of the use of the Full Service option.</p>
					<h6>(d) Confirmation.</h6>
					<p>Upon receipt of a credit card authorization from each individual purchase, Race IT generates a confirmation message and issues a unique confirmation number. If you are using the Service as an Organizer, you agree to unconditionally accept, honor, and fulfill all registration commitments that have been confirmed by Race IT through the Service, and it is your responsibility to verify the Buyer’s status, confirmation number and/or any event restrictions prior to the subject event.</p>
					<h6>(e) Other Services.</h6>
					<p>Race IT reserves the right to charge for Offline transaction initiated as a “no pay” registration, imported registrations, or registrations completed using 100% off codes as a result of social media or third party promotions (i.e. Groupon, Living Social, etc.). The standard rate for these types of transactions is a flat $2.10 per registration/unit. This charge does not apply to VIP codes or historic data uploaded into the system.</p>
					<p>Race IT will provide additional contract services as requested by the Customer. These services may include: e-mail distribution, SMS distribution, Social Media Marketing/Offers, web site development &amp; hosting, and custom development. This TAC does not contemplate and/or include such services. A separate fee schedule will be provided to the Customer for any or all of these services on a case by case basis. Please contact Race IT at support@RaceIT.com for more information.</p>
					<h5>5. YOUR REGISTRATION OBLIGATIONS.</h5>
					<p>To be a registered user of the Service, whether as an Organizer or Buyer, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Service registration form (the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or Race IT has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Race IT has the right to suspend or terminate your account and refuse any and all of your current or future use of the Service (or any portion thereof). Race IT is concerned about the safety and privacy of all its users, particularly children. For this reason, and to be consistent with the terms of use of any service provider or other third party service provider, you must be at least 18 years of age, or the legal age of majority where you reside if that jurisdiction has an older age of majority to register for an account.</p>
					<p>If you are an Organizer, you certify that you are, and at all times that you use the Service will continue to be, in full compliance with all sales tax registration, collection and payment obligations that may apply to any amounts paid by Buyers. If you are an Organizer, you further agree that you will indemnify and hold Race IT harmless against any amounts, imposed on Race IT by any taxing or other government authority, arising out of any such sales tax registration, collection and payment obligations.</p>
					<h5>6. THIRD PARTY APPLICATIONS.</h5>
					<p><strong>Links to Third Party Websites</strong>. The Site may contain links to third party web sites (“Linked Sites”). Race IT has no control over these Linked Sites or the content within them. Race IT cannot and does not guarantee, represent, or warrant that the content contained in the Linked Sites, including, without limitation other links, is accurate, legal, and/or inoffensive. Race IT does not endorse or guarantee the content of any Linked Site, nor do we warrant that a Linked Site will not contain computer viruses or other harmful code that can impact your computer or other web access device. By using the Site to link to a Linked Site, you agree and understand that such use is entirely at your own risk, and that you may not make any claim against Race IT for any damages or losses whatsoever resulting from such use.</p>
					<h5>7. ACCOUNT, PASSWORD AND SECURITY.</h5>
					<p>As part of the Service registration process, you will create a password and account. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. You agree to (a) immediately notify Race IT of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. Race IT cannot and will not be liable for any loss, damage or other liability arising from your failure to comply with this Section.</p>
					<h5>8. DMCA.</h5>
					<p>The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that any Content made available in connection with the Service infringes your copyright, you (or your agent) may send Race IT a notice requesting that the Content be removed, or access to it blocked. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA (see <a href="http://www.loc.gov/copyright" target="_blank">http://www.loc.gov/copyright</a> for details). Notices and counter notices with respect to the Service should be sent to Race IT at: By Mail:<br><br>9030 Stony Point Pkwy Suite 450<br>Richmond, VA 23235<br>By Email: <a href="mailto:support@raceit.com">support@raceit.com</a></p>
					<h5>9. INDEMNITY.</h5>
					<p>Whether you are using the Service as an Organizer, Buyer, Organizer Referrer, Buyer Referrer or otherwise, you agree to defend, indemnify and hold Race IT, and its affiliates, and their officers, agents, co-branders or other partners, and employees, harmless from any and all damage, loss, liability, cost and expense (including, without limitation, reasonable attorneys' and accounting fees) resulting from any claim, demand, suit or proceeding made by any third party ("Claim") due to or arising out of: Your Content; your use of, contribution to or connection with the Service (including the Referral Software); your violation of this TAC; or your violation of any rights of another. Race IT shall provide notice to you of any such Claim. Race IT reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this Section, and in such case, you agree to cooperate with all reasonable requests in assisting Race IT’s defense of such matter.</p>
					<h5>10. SERVICE MODIFICATIONS/SUSPENSIONS.</h5>
					<p>Race IT reserves the right at any time to, and from time to time may, modify, suspend or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. Race IT will not be responsible to you for a refund, in whole or part, of service charges for any reason, except with respect to refunds to Buyers that are expressly permitted under Section 4(b). You agree that Race IT shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
					<h5>11. TERMINATION.</h5>
					<p>Race IT, in its sole discretion, may terminate your password, account (or any part thereof) and/or your right to use the Service, and remove and discard any and all of Your Content within the Service, for any reason or no reason, including, without limitation, for lack of use, failure to timely pay any fees or other monies due Race IT, or if Race IT believes that you have violated or acted inconsistently with the letter or spirit of this TAC. You agree that any termination of your right to use the Service may be effected without prior notice, and acknowledge and agree that Race IT may immediately deactivate or delete your account and all related Content and files related to your account and/or bar any further access to such files or the Service. Further, you agree that Race IT shall not be liable to you or any third-party for any termination of your right to use or otherwise access the Service. All provisions of this TAC that by their nature should survive termination of your right to use the Service shall survive (including, without limitation, all limitations on liability, releases, indemnification obligations, disclaimers of warranties, and intellectual property protections).</p>
					<h5>12. DISCLAIMER OF WARRANTIES.</h5>
					<p>EXCEPT AS OTHERWISE SPECIFICALLY PROVIDED HEREIN, THE SERVICE IS PROVIDED HEREUNDER BY RACE IT <strong>“AS IS”</strong> WITHOUT WARRANTY OF ANY KIND.&nbsp; EXCEPT AS OTHERWISE SPECIFICALLY PROVIDED HEREIN, TO THE MAXIMUM EXTENT PERMITTED BY LAW, RACE IT EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, CONDITIONS, REPRESENTATIONS, AND GUARANTEES WITH RESPECT TO THE SERVICE, WHETHER EXPRESS OR IMPLIED, ARISING BY LAW, CUSTOM, PRIOR ORAL OR WRITTEN STATEMENTS, OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.&nbsp; NO REPRESENTATION OR OTHER AFFIRMATION OF FACT, INCLUDING, WITHOUT LIMITATION, STATEMENTS REGARDING CAPACITY, SUITABILITY FOR USE OR PERFORMANCE OF THE SERVICE, WHETHER MADE BY EMPLOYEES OF RACE IT OR OTHERWISE, WHICH IS NOT CONTAINED IN THIS AGREEMENT, SHALL BE DE EMED TO BE A WARRANTY BY RACE IT FOR ANY PURPOSE, OR GIVE RISE TO ANY LIABILITY OF RACE IT WHATSOEVER.</p>
					<h5>13. LIMITATION OF LIABILITY.</h5>
					<p>NEITHER PARTY SHALL BE LIABLE TO THE OTHER PARTY HERETO OR TO ANY THIRD PARTY FOR ANY INCIDENTAL, CONSEQUENTIAL, OR SPECIAL DAMAGES OF ANY KIND OR NATURE, INCLUDING WITHOUT LIMITATION, LOST PROFITS, LOSS OF DATA, OR FRUSTRATION OF BUSINESS EXPECTATIONS, WHETHER ARISING OUT OF SUCH PARTY’S BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, OR OTHERWISE (EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE).&nbsp; NEITHER PARTY SHALL ASSERT ANY SUCH CLAIM AGAINST THE OTHER OR ITS SUBSIDIARIES OR AFFILIATED COMPANIES OR THEIR RESPECTIVE OFFICERS, DIRECTORS, OR EMPLOYEES. &nbsp;RACE IT’S MAXIMUM LIABILITY HEREUNDER FOR ANY CLAIMS WHATSOEVER IS EXPRESSLY LIMITED TO THE AMOUNT PAID UNDER THIS AGREEMENT BY CUSTOMER TO USRACEWORKS DURING THE 3-MONTH PERIOD IMMEDIATELY PRECEDING THE CAUSE GIVING RISE TO THE CLAIM, IF ANY.&nbsp; NO CLAIM MAY BE BROUGHT BY THE CUSTOMER OR ANY OF ITS AFFILIATES UNDER THIS AGREEMENT MORE THAN ONE YEAR AFTER THE ACCRUAL OF THE CLAIM.<br><br></p>
					<h5>14. ASSIGNMENT.</h5>
					<p>This TAC shall inure to the benefit of, and shall be binding upon, both parties and their respective successors and permitted assigns. Neither party may assign or delegate this TAC or any of its rights or duties under this TAC without the prior written consent of the other party, except as expressly set forth herein or to an individual or entity into which it has merged or which has otherwise succeeded to all or substantially all of the assets or equity securities of the assignor, and which has assumed in writing or by operation of law, the assignor’s obligations under this TAC.</p>
					<h5>15. PRIVACY.</h5>
					<p>All information provided by you or collected by Race IT in connection with the Service is governed by Race IT’s Privacy Policy, a copy of which is located at <a href="/legal/privacy-policy.aspx">http://www.raceit.com/legal/privacy-policy.aspx</a> , which is hereby incorporated by reference into this TAC. Race IT strongly recommends that you review the Privacy Policy closely. In particular, Event Organizers should note that Race IT may use information it receives or collects regarding Buyers in accordance with the terms of its Privacy Policy. Further, any information submitted or provided by you to the Service may be publicly accessible. You should take care to protect private information or information that is important to you. Race IT shall not be responsible for protecting any such information and is not liable for the protection of privacy of electronic mail or other information transferred through the Internet or any other network that you may use. Please be aware that if you decide to disclose personally identifiable information on the Service, this information may become public. Race IT does not control and shall not be responsible for the acts of you or any other users of the Service.</p>
					<h5>16. NOTICE.</h5>
					<p>Any notice or correspondence required or permitted to be given or forwarded hereunder or by law shall be effective on receipt and shall be considered properly given if in writing and delivered personally or faxed with confirmation or sent by any commercially reasonable means of receipted delivery, addressed, with respect to Customer, to the address of Customer most recently provided in writing to Race IT, and with respect to Race IT, to the address of Race IT appearing on its web site at the time of such notice.</p>
					<h5>17. GENERAL.</h5>
					<p>This Agreement represents the complete understanding and agreement of the parties hereto with respect to the subject matter hereof and supersedes any prior or contemporaneous agreements, whether written or oral, between the parties.&nbsp; This Agreement may not be modified or amended, except by a written instrument executed by each of the parties hereto.&nbsp; This Agreement is for the sole benefit of the parties hereto and is not for the benefit of any third party.&nbsp; The parties hereto shall be deemed to be independent contractors hereunder, and as such, neither party shall be, nor hold itself out to be, an employee or agent of the other party.&nbsp; The language used in this Agreement shall be deemed to be language chosen by both parties hereto to express their mutual intent, and no rule of strict construction against either party shall apply to licenses granted herein or to any term of condition of this Agreement.</p>
					<h5>18. GOVERNING LAW.</h5>
					<p>This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of Virginia, and the parties here to shall submit to the exclusive jurisdiction of Virginia Courts or any Federal Court sitting in Virginia.</p>
					<h5>19. VIOLATIONS.</h5>
					<p>Please report any violations of this TAC by email to <a href="mailto:support@raceit.com">support@RaceIT.com</a>.</p>
					
			</div><!-- .entry-content -->

		</article><!-- #post-## -->

	</main>
@endsection